#!/bin/sh
set -x

cd crossbar
chmod 777 .
docker run -u 1000 -v ${PWD}:/node -p 8080:8080 --name crossbar --rm crossbario/crossbar &
cd ..

sleep 20

php tests/Crossbar/crossbarClient.php &
sleep 2
vendor/bin/phpunit tests/Crossbar/CrossbarTest.php

exit $?