#!/bin/sh

/usr/local/bin/crossbar init --template hello:php --appdir $HOME/hello

cd $HOME/hello

make install

#Tests need to be run against dev-master, not the latest stable
composer require "voryx/thruway":"dev-master"
